---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitops-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: git-push-trigger
      bindings:
        - ref: git-push-binding
      template:
        ref: git-trigger-template
