---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-deploy
spec:
  workspaces:
    - name: source
    - name: ssh-directory
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        
        cd $(workspaces.source.path)
        pwd
        echo "Deploying using kustomize overlay: apps/manifests/overlays/prod"        
        cd apps/manifests/overlays/prod
        ls -l
        kubectl apply -k .
