---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-deploy
spec:
  workspaces:
    - name: source
    - name: ssh-directory
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e

        cd $(workspaces.source.path)/gitops
        echo "Current directory:"
        pwd
        ls -l

        echo "Deploying using kustomize overlay: apps/manifests/overlays/prod"
        cd apps/manifests/overlays/prod

        echo "Contents of kustomization.yaml file(if exists):"
        cat kustomization.yaml || echo "kustomization.yaml not found!"

        echo "Applying manifests with kubectl:"
        kubectl apply -k .
