---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: odo-deploy
spec:
  steps:
    - name: deploy
      image: registry.access.redhat.com/ubi8/nodejs-16
      script: |
        #!/bin/sh
        curl -L https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o odo
        chmod +x odo && mv odo /usr/local/bin/
        odo deploy
