---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-kustomize-image
spec:
  params:
    - name: gitops-repo-url
    - name: image
    - name: app-name
    - name: branch
  # resources:
  #   inputs:
  #     resources:
  #       - name: workspace
  #         type: git
  #         targetPath: target-workspace
  #   outputs:
  #     resources:
  #       - name: build-sources
  #         type: ubuntu
  workspaces:
    - name: output
  steps:
    - name: update
      image: alpine/git
      script: |
        set -e
        cd $(workspaces.output.path)
        git clone --branch $(params.branch) $(params.gitops-repo-url) gitops
        cd gitops

        echo "updating image in kustomization.yaml"
        sed -i "s|newTag:.*|newTag: $(echo $(params.image) | cut -d: -f2)|" kustomization.yaml

        git config user.name "Bhavesh Patel"
        git config user.email "tekton@example.com"
        git add kustomization.yaml
        git commit -m "update image to $(params.image)"
        git push origin $(params.branch)