---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-kustomize-image
spec:
  params:
    - name: gitops-repo-url
    - name: image
    - name: app-name
    - name: branch
  workspaces:
    - name: source
    - name: ssh-directory
  steps:
    - name: update
      image: docker.io/alpine/git:latest
      script: |
        set -e

        mkdir -p ~/.ssh
        cp $(workspaces.ssh-directory.path)/id_rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        cd $(workspaces.source.path)
        git clone --branch $(params.branch) $(params.gitops-repo-url) gitops
        cd apps/manifests/overlays/prod

        echo "kustomization.yaml before:"
        echo "--------------------------"
        cat kustomization.yaml

        echo "updating image in kustomization.yaml"
        sed -i "s|newTag:.*|newTag: $(echo $(params.image) | cut -d: -f2)|" kustomization.yaml
        
        echo "kustomization.yaml after:"
        echo "--------------------------"
        cat kustomization.yaml

        cd $(workspaces.source.path)
        git config user.name "Bhavesh Patel"
        git config user.email "bhavesh.scp@hotmail.com"
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add kustomization.yaml
          git commit -m "update image to $(params.image)"
          git push origin $(params.branch)
        fi
