---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-kustomize-image
spec:
  params:
    - name: gitops-repo-url
    - name: image
    - name: app-name
    - name: branch
  workspaces:
    - name: source
    - name: ssh-directory
  steps:
    - name: update
      image: docker.io/alpine/git:latest
      script: |
        set -e

        mkdir -p ~/.ssh
        cp $(workspaces.ssh-directory.path)/id_rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        KUSTOMIZATION_FILE_PATH=apps/manifests/overlays/prod/kustomization.yaml

        cd $(workspaces.source.path)
        ls -l
        git clone --branch $(params.branch) $(params.gitops-repo-url) gitops

        echo "Checking base directory:"
        ls -l $(workspaces.source.path)/apps/manifests/base

        echo "Contents of base kustomization.yaml:"
        cat $(workspaces.source.path)/apps/manifests/base/kustomization.yaml || echo "Missing base kustomization.yaml"

        echo "$KUSTOMIZATION_FILE_PATH before change:"
        echo "--------------------------"
        cat $KUSTOMIZATION_FILE_PATH

        echo "updating image in kustomization.yaml"
        sed -i "s|newTag:.*|newTag: $(echo $(params.image) | cut -d: -f2)|" $KUSTOMIZATION_FILE_PATH
        
        echo "$KUSTOMIZATION_FILE_PATH after change:"
        echo "--------------------------"
        cat $KUSTOMIZATION_FILE_PATH
        
        cd gitops
        git config user.name "Bhavesh Patel"
        git config user.email "bhavesh.scp@hotmail.com"
        git status
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add $KUSTOMIZATION_FILE_PATH
          git commit -m "update image to $(params.image)"
          git push origin $(params.branch)
        fi
