---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: python-image
    newName: docker.io/bhaveshscp/python-image
    newTag: 78f3e2a814c6c939907fad979a43adb448d11bc6
