---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
images:
  - name: python-image
    newName: docker.io/bhaveshscp/python-image
    newTag: 82368dd22d3690890e622d37a0b9a0399edeb59b
