---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-deployer
  namespace: mywebapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: mywebapp
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "services", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
  namespace: mywebapp
subjects:
  - kind: ServiceAccount
    name: pipeline-deployer
    namespace: mywebapp
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
