---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ci-gitops-pipeline-run
  annotations:
    pipelinesascode.tekton.dev/on-event: pull_request
    pipelinesascode.tekton.dev/on-target-branch: main
spec:
  pipelineRef:
    name: ci-gitops-pipeline
  params:
    - name: repo-url
      value: https://github.com/bscp7/python-webapp.git
    - name: image-url
      value: docker.io/bhaveshscp/python-image
    - name: gitops-repo-url
      value: https://github.com/bscp7/python-webapp.git
    - name: app-name
      value: mywebapp
    - name: gitops-branch
      value: main
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: ssh-creds
      secret:
        secretName: git-ssh-key
