apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-gitops-pipeline
spec:
  params:
    - name: repo-url
    - name: image-url
    - name: gitops-repo-url
    - name: app-name
    - name: gitops-branch
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      runAfter:
        - clone-source
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.clone-source.results.commit)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: patch-gitops
      taskRef:
        name: update-kustomize-image
      runAfter:
        - build-image
      params:
        - name: gitops-repo-url
          value: $(params.gitops-repo-url)
        - name: image
          value: $(params.image-url):$(tasks.clone-source.results.commit)
        - name: app-name
          value: $(params.app-name)
        - name: branch
          value: $(params.gitops-branch)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: deploy
      taskRef:
        name: kubectl-deploy
      runAfter:
        - patch-gitops
      workspaces:
        - name: source
          workspace: shared-workspace
