name: Deploy to OpenShift using odo

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up odo CLI
        run: |
          curl -L https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o odo
          chmod +x odo
          sudo mv odo /usr/local/bin/

      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          odo login --token $OPENSHIFT_TOKEN --server $OPENSHIFT_SERVER

      - name: Deploy with odo
        run: |
          odo deploy
